name: Java CI with Maven, Docker

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      image: ringvorlesunghszg:main
      ports: 8080:8080
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: check app is ready to test
        run: curl --noproxy "*" -kv --connect-timeout 30 --retry 300 --retry-delay 5 --retry-connrefused http://localhost:8080
      - name: Build CucumberTest with Maven
        run: mvn clean install -DskipTests --file bddtest/cucumber/pom.xml