name: Test App with JBehave

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      app:
        image: ghcr.io/wolffj1995/ringvorlesunghszg:main
        ports:
          - 8080:8080
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: check app is ready to test
        run: curl --noproxy "*" -kv --connect-timeout 30 --retry 300 --retry-delay 5 --retry-connrefused http://localhost:8080
      - name: Build with Maven
        run: mvn clean test -Dtest=RunAllBddStories -Dspring.profiles.active=set_development --file bddtest/jbehave/pom.xml
      - uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber.json"
      - name: Deploy report page to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target